# File: .github/workflows/qa.yml

on:
  release:
    types:
      - "published"
  workflow_dispatch:

name: Publish Module to PSGallery

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Az.Resources module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az.Resources

      - name: Publish module
        shell: pwsh
        id: publish-module
        run: |
          Publish-Module -Path ./src/PSWattTime -NuGetApiKey ${{ secrets.PS_GALLERY_KEY }}
