# File: .github/workflows/qa.yml

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'releases/**'

name: PowerShell Module Quality Assurance

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Az PowerShell Module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.0
        with:
          path: .\
          recurse: true 
          output: results.sarif
          excludeRule: '"PSAvoidUsingPlainTextForPassword"'

      - name: Run Pester tests
        shell: pwsh
        env:
          WATTTIMEUSERNAME: ${{ secrets.WATTTIMEUSERNAME }}
          WATTTIMEPASSWORD: ${{ secrets.WATTTIMEPASSWORD }}
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az.Resources
          Import-Module Az.Resources
          Import-Module Pester
          $pConfig = New-PesterConfiguration
          $pConfig.Output.CIFormat = 'GithubActions'
          $pConfig.Output.Verbosity = 'Detailed'
          $pConfig.TestResult.OutputFormat = 'JunitXml'
          $pConfig.TestResult.OutputPath ='./tests/junit.xml'
          $pConfig.TestResult.Enabled = $true
          $p = Invoke-Pester ./tests/PSWattTime.Tests/PSWattTime.Tests.ps1 `
            -PassThru `
            -CodeCoverage ./src/PSWattTime/PSWattTime.psm1 `
            -CodeCoverageOutputFile ./tests/coverage.xml `
            -CodeCoverageOutputFileFormat JaCoCo `
            -Configuration $pConfig
          Write-Output "## Pester Test Results" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "- Code coverage: **$($p.CodeCovergage.CodeCoveragePercent)**" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "- Commands Executed: **$($p.CodeCovergage.CommandsExecutedCount)**" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "- Commands Missed: **$($p.CodeCovergage.CommandsMissedCount)**" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "|Block|Test|Duration|Result|" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "|---|---|---|---|" >> $env:GITHUB_STEP_SUMMARY
          $p.Tests | ForEach-Object {
            $mdTestResult = ""
            If($_.Result -eq 'Failed') {
              $mdTestResult = ":boom: Failed"
            }
            ElseIf($_.Result -eq 'Passed') {
              $mdTestResult = ":green_heart: Passed"
            }
            Else {
              $mdTestResult = ":nerd_face: $($_.Result)"
            }
            Write-Output "|$($_.Block)|$($_.Name)|$($_.Duration)|$($mdTestResult)|"
          } >> $env:GITHUB_STEP_SUMMARY
          Write-Output "" >> $env:GITHUB_STEP_SUMMARY

      - name: Test the Module Manifest
        shell: pwsh
        run: Test-ModuleManifest -Path ./src/PSWattTime/PSWattTime.psd1

      - name: Run the GitHub action in this commit
        uses: cloudyspells/PSWattTime@main
        id: watttime_action
        with:
          azure_credential: ${{ secrets.AZURE_CREDENTIALS }}
          watttime_username: ${{ secrets.WATTTIMEUSERNAME }}
          watttime_password: ${{ secrets.WATTTIMEPASSWORD }}
          regions: '"westeurope","northeurope","uksouth","francecentral","germanynorth"'

      - name: Echo region from action
        run: |
          echo 'Best emissions region: ${{ steps.watttime_action.outputs.region }}'

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests
          path: ./tests/*.xml
        if: ${{ always() }}
